// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc task.30.0
// source: task.status.sql

package sqlc

import (
	"context"

	"final/internal/models"
	"github.com/jackc/pgx/v5/pgtype"
)

const updateTaskStatus = `-- name: UpdateTaskStatus :one
UPDATE tasks
SET status = $2,
    updated_at = NOW()
WHERE id = $1
    RETURNING id, title, content, status, created_at, updated_at
`

type UpdateTaskStatusParams struct {
	ID     int64             `json:"id"`
	Status models.TaskStatus `json:"status"`
}

type UpdateTaskStatusRow struct {
	ID        int64              `json:"id"`
	Title     string             `json:"title"`
	Content   string             `json:"content"`
	Status    models.TaskStatus  `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateTaskStatus(ctx context.Context, arg *UpdateTaskStatusParams) (*UpdateTaskStatusRow, error) {
	row := q.db.QueryRow(ctx, updateTaskStatus, arg.ID, arg.Status)
	var i UpdateTaskStatusRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
