// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: task.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (title, content, status, done, created_at)
VALUES ($1, $2, $3, $4, NOW())
    RETURNING id, user_id, title, content, status, done, created_at, updated_at, deleted_at
`

type CreateTaskParams struct {
	Title   string      `json:"title"`
	Content pgtype.Text `json:"content"`
	Status  string      `json:"status"`
	Done    bool        `json:"done"`
}

func (q *Queries) CreateTask(ctx context.Context, arg *CreateTaskParams) (*Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.Title,
		arg.Content,
		arg.Status,
		arg.Done,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Content,
		&i.Status,
		&i.Done,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const deleteTask = `-- name: DeleteTask :exec
UPDATE tasks
SET deleted_at = NOW()
WHERE id = $1
`

func (q *Queries) DeleteTask(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteTask, id)
	return err
}

const doneTask = `-- name: DoneTask :exec
UPDATE tasks
SET done = TRUE,
    status = 'done'
WHERE id = $1
`

func (q *Queries) DoneTask(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, doneTask, id)
	return err
}

const getTaskByID = `-- name: GetTaskByID :one
SELECT id, user_id, title, content, status, done, created_at, updated_at, deleted_at FROM tasks WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTaskByID(ctx context.Context, id int64) (*Task, error) {
	row := q.db.QueryRow(ctx, getTaskByID, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Content,
		&i.Status,
		&i.Done,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const listTasks = `-- name: ListTasks :many
SELECT id, user_id, title, content, status, done, created_at, updated_at, deleted_at FROM tasks ORDER BY created_at DESC
`

func (q *Queries) ListTasks(ctx context.Context) ([]*Task, error) {
	rows, err := q.db.Query(ctx, listTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Content,
			&i.Status,
			&i.Done,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
