// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: sync/final-boss/v1/tasks.proto

package tsk1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Done          bool                   `protobuf:"varint,4,opt,name=done,proto3" json:"done,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_sync_final_boss_v1_tasks_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_sync_final_boss_v1_tasks_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_sync_final_boss_v1_tasks_proto_rawDescGZIP(), []int{0}
}

func (x *Task) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Task) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Task) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Task) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *Task) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// --- Create ---
type CreateTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskRequest) Reset() {
	*x = CreateTaskRequest{}
	mi := &file_sync_final_boss_v1_tasks_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskRequest) ProtoMessage() {}

func (x *CreateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sync_final_boss_v1_tasks_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateTaskRequest) Descriptor() ([]byte, []int) {
	return file_sync_final_boss_v1_tasks_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTaskRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateTaskRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type CreateTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskResponse) Reset() {
	*x = CreateTaskResponse{}
	mi := &file_sync_final_boss_v1_tasks_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskResponse) ProtoMessage() {}

func (x *CreateTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sync_final_boss_v1_tasks_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskResponse.ProtoReflect.Descriptor instead.
func (*CreateTaskResponse) Descriptor() ([]byte, []int) {
	return file_sync_final_boss_v1_tasks_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

// --- List ---
type ListTasksRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// если 0 — вернуть все
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksRequest) Reset() {
	*x = ListTasksRequest{}
	mi := &file_sync_final_boss_v1_tasks_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksRequest) ProtoMessage() {}

func (x *ListTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sync_final_boss_v1_tasks_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksRequest.ProtoReflect.Descriptor instead.
func (*ListTasksRequest) Descriptor() ([]byte, []int) {
	return file_sync_final_boss_v1_tasks_proto_rawDescGZIP(), []int{3}
}

func (x *ListTasksRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*Task                `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksResponse) Reset() {
	*x = ListTasksResponse{}
	mi := &file_sync_final_boss_v1_tasks_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksResponse) ProtoMessage() {}

func (x *ListTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sync_final_boss_v1_tasks_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksResponse.ProtoReflect.Descriptor instead.
func (*ListTasksResponse) Descriptor() ([]byte, []int) {
	return file_sync_final_boss_v1_tasks_proto_rawDescGZIP(), []int{4}
}

func (x *ListTasksResponse) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

// --- Delete ---
type DeleteTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTaskRequest) Reset() {
	*x = DeleteTaskRequest{}
	mi := &file_sync_final_boss_v1_tasks_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTaskRequest) ProtoMessage() {}

func (x *DeleteTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sync_final_boss_v1_tasks_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTaskRequest.ProtoReflect.Descriptor instead.
func (*DeleteTaskRequest) Descriptor() ([]byte, []int) {
	return file_sync_final_boss_v1_tasks_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteTaskRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTaskResponse) Reset() {
	*x = DeleteTaskResponse{}
	mi := &file_sync_final_boss_v1_tasks_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTaskResponse) ProtoMessage() {}

func (x *DeleteTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sync_final_boss_v1_tasks_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTaskResponse.ProtoReflect.Descriptor instead.
func (*DeleteTaskResponse) Descriptor() ([]byte, []int) {
	return file_sync_final_boss_v1_tasks_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteTaskResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// --- Done ---
type DoneTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoneTaskRequest) Reset() {
	*x = DoneTaskRequest{}
	mi := &file_sync_final_boss_v1_tasks_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoneTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoneTaskRequest) ProtoMessage() {}

func (x *DoneTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sync_final_boss_v1_tasks_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoneTaskRequest.ProtoReflect.Descriptor instead.
func (*DoneTaskRequest) Descriptor() ([]byte, []int) {
	return file_sync_final_boss_v1_tasks_proto_rawDescGZIP(), []int{7}
}

func (x *DoneTaskRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DoneTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoneTaskResponse) Reset() {
	*x = DoneTaskResponse{}
	mi := &file_sync_final_boss_v1_tasks_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoneTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoneTaskResponse) ProtoMessage() {}

func (x *DoneTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sync_final_boss_v1_tasks_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoneTaskResponse.ProtoReflect.Descriptor instead.
func (*DoneTaskResponse) Descriptor() ([]byte, []int) {
	return file_sync_final_boss_v1_tasks_proto_rawDescGZIP(), []int{8}
}

func (x *DoneTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

var File_sync_final_boss_v1_tasks_proto protoreflect.FileDescriptor

const file_sync_final_boss_v1_tasks_proto_rawDesc = "" +
	"\n" +
	"\x1esync/final-boss/v1/tasks.proto\x12\btasks.v1\x1a\x17validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\"r\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x12\n" +
	"\x04done\x18\x04 \x01(\bR\x04done\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\"X\n" +
	"\x11CreateTaskRequest\x12\x1f\n" +
	"\x05title\x18\x01 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x18dR\x05title\x12\"\n" +
	"\acontent\x18\x02 \x01(\tB\b\xfaB\x05r\x03\x18\xe8\aR\acontent\"8\n" +
	"\x12CreateTaskResponse\x12\"\n" +
	"\x04task\x18\x01 \x01(\v2\x0e.tasks.v1.TaskR\x04task\"+\n" +
	"\x10ListTasksRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02(\x00R\x02id\"9\n" +
	"\x11ListTasksResponse\x12$\n" +
	"\x05tasks\x18\x01 \x03(\v2\x0e.tasks.v1.TaskR\x05tasks\",\n" +
	"\x11DeleteTaskRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x02id\".\n" +
	"\x12DeleteTaskResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"*\n" +
	"\x0fDoneTaskRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x02id\"6\n" +
	"\x10DoneTaskResponse\x12\"\n" +
	"\x04task\x18\x01 \x01(\v2\x0e.tasks.v1.TaskR\x04task2\x83\x03\n" +
	"\x05Tasks\x12]\n" +
	"\n" +
	"CreateTask\x12\x1b.tasks.v1.CreateTaskRequest\x1a\x1c.tasks.v1.CreateTaskResponse\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/tasks\x12W\n" +
	"\tListTasks\x12\x1a.tasks.v1.ListTasksRequest\x1a\x1b.tasks.v1.ListTasksResponse\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/v1/tasks\x12_\n" +
	"\n" +
	"DeleteTask\x12\x1b.tasks.v1.DeleteTaskRequest\x1a\x1c.tasks.v1.DeleteTaskResponse\"\x16\x82\xd3\xe4\x93\x02\x10*\x0e/v1/tasks/{id}\x12a\n" +
	"\bDoneTask\x12\x19.tasks.v1.DoneTaskRequest\x1a\x1a.tasks.v1.DoneTaskResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\x1a\x13/v1/tasks/{id}/doneB$Z\"final/pkg/proto/sync/final/v1;tsk1b\x06proto3"

var (
	file_sync_final_boss_v1_tasks_proto_rawDescOnce sync.Once
	file_sync_final_boss_v1_tasks_proto_rawDescData []byte
)

func file_sync_final_boss_v1_tasks_proto_rawDescGZIP() []byte {
	file_sync_final_boss_v1_tasks_proto_rawDescOnce.Do(func() {
		file_sync_final_boss_v1_tasks_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sync_final_boss_v1_tasks_proto_rawDesc), len(file_sync_final_boss_v1_tasks_proto_rawDesc)))
	})
	return file_sync_final_boss_v1_tasks_proto_rawDescData
}

var file_sync_final_boss_v1_tasks_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_sync_final_boss_v1_tasks_proto_goTypes = []any{
	(*Task)(nil),               // 0: tasks.v1.Task
	(*CreateTaskRequest)(nil),  // 1: tasks.v1.CreateTaskRequest
	(*CreateTaskResponse)(nil), // 2: tasks.v1.CreateTaskResponse
	(*ListTasksRequest)(nil),   // 3: tasks.v1.ListTasksRequest
	(*ListTasksResponse)(nil),  // 4: tasks.v1.ListTasksResponse
	(*DeleteTaskRequest)(nil),  // 5: tasks.v1.DeleteTaskRequest
	(*DeleteTaskResponse)(nil), // 6: tasks.v1.DeleteTaskResponse
	(*DoneTaskRequest)(nil),    // 7: tasks.v1.DoneTaskRequest
	(*DoneTaskResponse)(nil),   // 8: tasks.v1.DoneTaskResponse
}
var file_sync_final_boss_v1_tasks_proto_depIdxs = []int32{
	0, // 0: tasks.v1.CreateTaskResponse.task:type_name -> tasks.v1.Task
	0, // 1: tasks.v1.ListTasksResponse.tasks:type_name -> tasks.v1.Task
	0, // 2: tasks.v1.DoneTaskResponse.task:type_name -> tasks.v1.Task
	1, // 3: tasks.v1.Tasks.CreateTask:input_type -> tasks.v1.CreateTaskRequest
	3, // 4: tasks.v1.Tasks.ListTasks:input_type -> tasks.v1.ListTasksRequest
	5, // 5: tasks.v1.Tasks.DeleteTask:input_type -> tasks.v1.DeleteTaskRequest
	7, // 6: tasks.v1.Tasks.DoneTask:input_type -> tasks.v1.DoneTaskRequest
	2, // 7: tasks.v1.Tasks.CreateTask:output_type -> tasks.v1.CreateTaskResponse
	4, // 8: tasks.v1.Tasks.ListTasks:output_type -> tasks.v1.ListTasksResponse
	6, // 9: tasks.v1.Tasks.DeleteTask:output_type -> tasks.v1.DeleteTaskResponse
	8, // 10: tasks.v1.Tasks.DoneTask:output_type -> tasks.v1.DoneTaskResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_sync_final_boss_v1_tasks_proto_init() }
func file_sync_final_boss_v1_tasks_proto_init() {
	if File_sync_final_boss_v1_tasks_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sync_final_boss_v1_tasks_proto_rawDesc), len(file_sync_final_boss_v1_tasks_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sync_final_boss_v1_tasks_proto_goTypes,
		DependencyIndexes: file_sync_final_boss_v1_tasks_proto_depIdxs,
		MessageInfos:      file_sync_final_boss_v1_tasks_proto_msgTypes,
	}.Build()
	File_sync_final_boss_v1_tasks_proto = out.File
	file_sync_final_boss_v1_tasks_proto_goTypes = nil
	file_sync_final_boss_v1_tasks_proto_depIdxs = nil
}
